### ISSUE TITLE
yacman dev breaks bulker

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#45]
Haven't had time to figure this out yet, but if install yacman-0.8.0-dev0 from `dev` right now, then bulker fails with:

```
 ba databio/sciquill
Bulker config: /home/nsheff/Dropbox/env/bulker_config/zither.yaml
Activating bulker crate: databio/sciquill
Your bulker config file is outdated, you need to re-initialize it: _file_path
```

with the current release version, bulker is fine.

**Comment by stolarczyk** [comment]
That's because bulker uses a private attribute of the YacAttMap class, which has changed. It should use the official property instead: 'YacAttMap.file_path'

**Comment by nsheff** [comment]
but wouldn't that prevent the YacAttMap object from having a real `file_path` property, from the config file?

**Comment by stolarczyk** [comment]
I'm not sure I understand. What do you mean by real?

**Comment by nsheff** [comment]
say my yaml file is:

```yaml
file_type: bed
file_path: /path/to/file.bed
cell_line: K562
```

Now what? You're saying `YAM.file_path` is a built-in property pointing to the config file? Then what happens with the clash when I have an actual property with that name?

We can't set properties that could clash, right? Or am I forgetting something?

**Comment by stolarczyk** [comment]
Yeah, that's a problem... It is a general issue with any object attribute that is stored, even with the previous one: `_file_path`. Admittedly, that's a less frequent scenario.

That's because we mix the "object content" with the "object state". Unless we split these into two spaces somehow, there will be no solution to this issue, I guess.

**Comment by nsheff** [comment]
I see no value in switching from `_file_path` to `file_path` and I see lots of value in keeping `_file_path`, because to me it clarifies that this is an meta-entity and not a config attribute. I might even argue that all meta-entities should start with underscores....

But particularly for something like `file_path`,  which is very likely to be an actual config attribute in some config file somewhere.  `_file_path` not so much.

**Comment by stolarczyk** [comment]
I see your point. I'd like to solve it as well as we can, though.`_file_path` is just one of 9 such properties (the count will likely increase in the future), all of them start with underscores:

https://github.com/databio/yacman/blob/29951a94399d40985ffcec68d1cdff56301e764b/yacman/const.py#L5-L13

Let's just have one key reserved for these, which is obviously not visible to the end-user. We can give it some wild name to make "sure" it's unlikely to be used as a key to store values by others. We could even add a check in `YacAttMap.__setitem__` to prevent using this reserved key. 
Then we implement dedicated _methods_, not properties to retrieve these meta values, like: `YacAttMap.get_file_path()` instead of `YacAttMap.file_path`, to avoid collisions.

what do you think?

**Comment by nsheff** [comment]
I like the idea of one key reserved. but the methods are also problematic as well for the same reason -- now you can't have a property called `get_file_path`. Why not just put them under that  one reserved key, so it's also how you access methods? So, say it's `_internal` as our reserved key, it would be:

```
yam = YacAttMap(...)
yam.my_attribute  # use yam.X to get your attributes
yam._internal.file_path  # use yam._internal.X to get build-in attributes/methods
yam._internal.get_file_path  # maybe not necessary with this approach?
```

basically, I want to avoid `yam.get_file_path`

The alternative would be to put all the yaml attributes under a separate attribute, which would reduce clashing even further, but is annoying in use. like:

```
yam.attributes.my_attr  # use yam.attribute.X to get your stuff
yam.file_path # built-in stuff is top-level
```

**Comment by nsheff** [comment]
Also, moving all the internal variables to a single key is a good idea but I think we should maintain backwards compatibility for a few cycles to give us time to update all the packages that rely on yacman.
